# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ['master']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::733905840417:role/ammobin-github-actions-role
          aws-region: ca-central-1
       

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: synth
        run: |
          npm run cdk synth
      - name: cdk deploy global
        uses: scottbrenner/aws-cdk-action@v1.5.0
        with:
          args: 'deploy AmmobinGlobalCdkStack'
        env:
          AWS_DEFAULT_REGION: 'us-east-1'
      - name: cdk deploy api ca prod
        uses: scottbrenner/aws-cdk-action@v1.5.0
        with:
          args: 'deploy AmmobinCdkStack'
        env:
          AWS_DEFAULT_REGION: 'ca-central-1'

